-- =====================================================================
-- Snowflake DDL for Logistics Weather Risk Engine Star Schema
-- Database: WEATHER_DB | Schema: WEATHER_SCHEMA
-- =====================================================================

-- 1. Dimension Table: Hubs (Origin and Destination Ports/Airports)
CREATE TABLE IF NOT EXISTS DIM_HUBS (
    HUB_ID VARCHAR(50) PRIMARY KEY,
    HUB_NAME VARCHAR(100) NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    HUB_TYPE VARCHAR(20) NOT NULL -- 'AIRPORT' or 'PORT'
);

-- 2. Dimension Table: Shipments
CREATE TABLE IF NOT EXISTS DIM_SHIPMENTS (
    SHIPMENT_ID VARCHAR(50) PRIMARY KEY,
    CARGO_TYPE VARCHAR(50) NOT NULL, -- 'PHARMACEUTICALS', 'ELECTRONICS', 'GENERAL_MERCHANDISE'
    CARGO_VALUE_USD FLOAT NOT NULL,
    ORIGIN_HUB_ID VARCHAR(50) REFERENCES DIM_HUBS(HUB_ID),
    DESTINATION_HUB_ID VARCHAR(50) REFERENCES DIM_HUBS(HUB_ID),
    DEPARTURE_TIME TIMESTAMP_NTZ NOT NULL,
    ARRIVAL_TIME TIMESTAMP_NTZ NOT NULL
);

-- 3. Fact Table: Weather Forecasts
CREATE TABLE IF NOT EXISTS FACT_WEATHER_FORECAST (
    FORECAST_ID VARCHAR(100) PRIMARY KEY, -- Composite key, e.g., 'HUB_ID_DATE'
    HUB_ID VARCHAR(50) REFERENCES DIM_HUBS(HUB_ID),
    FORECAST_DATE DATE NOT NULL,
    MAX_TEMP_C FLOAT,
    MIN_TEMP_C FLOAT,
    MAX_WIND_SPEED_KMH FLOAT,
    PRECIPITATION_PROBABILITY FLOAT, -- Percentage (0 - 100)
    WEATHER_CODE INT,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Fact Table: Shipment Risk Alerts
CREATE TABLE IF NOT EXISTS FACT_SHIPMENT_RISK_ALERTS (
    ALERT_ID VARCHAR(100) PRIMARY KEY, -- Composite key, e.g., 'SHIPMENT_ID_TIMESTAMP'
    SHIPMENT_ID VARCHAR(50) REFERENCES DIM_SHIPMENTS(SHIPMENT_ID),
    ROUTE_RISK_SCORE FLOAT NOT NULL, -- Risk index from 0 to 100
    RISK_LEVEL VARCHAR(10) NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH'
    RISK_REASON VARCHAR(500), -- Reasoning behind high risk score
    EVALUATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================================================
-- Seed Data for DIM_HUBS (Initializing with global transit hubs)
-- =====================================================================
MERGE INTO DIM_HUBS AS target
USING (
    SELECT 'MUM' AS HUB_ID, 'Mumbai International Airport' AS HUB_NAME, 19.0760 AS LATITUDE, 72.8777 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'NYC' AS HUB_ID, 'John F. Kennedy International Airport' AS HUB_NAME, 40.7128 AS LATITUDE, -74.0060 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'LON' AS HUB_ID, 'London Heathrow Airport' AS HUB_NAME, 51.5074 AS LATITUDE, -0.1278 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'TYO' AS HUB_ID, 'Tokyo Haneda Airport' AS HUB_NAME, 35.6762 AS LATITUDE, 139.6503 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'SYD' AS HUB_ID, 'Sydney Kingsford Smith Airport' AS HUB_NAME, -33.8688 AS LATITUDE, 151.2093 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'PAR' AS HUB_ID, 'Paris Charles de Gaulle Airport' AS HUB_NAME, 48.8566 AS LATITUDE, 2.3522 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'BER' AS HUB_ID, 'Berlin Brandenburg Airport' AS HUB_NAME, 52.5200 AS LATITUDE, 13.4050 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'DXB' AS HUB_ID, 'Dubai International Airport' AS HUB_NAME, 25.2048 AS LATITUDE, 55.2708 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'SIN' AS HUB_ID, 'Singapore Changi Airport' AS HUB_NAME, 1.3521 AS LATITUDE, 103.8198 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE UNION ALL
    SELECT 'LAX' AS HUB_ID, 'Los Angeles International Airport' AS HUB_NAME, 34.0522 AS LATITUDE, -118.2437 AS LONGITUDE, 'AIRPORT' AS HUB_TYPE
) AS source
ON target.HUB_ID = source.HUB_ID
WHEN MATCHED THEN
    UPDATE SET 
        target.HUB_NAME = source.HUB_NAME,
        target.LATITUDE = source.LATITUDE,
        target.LONGITUDE = source.LONGITUDE,
        target.HUB_TYPE = source.HUB_TYPE
WHEN NOT MATCHED THEN
    INSERT (HUB_ID, HUB_NAME, LATITUDE, LONGITUDE, HUB_TYPE)
    VALUES (source.HUB_ID, source.HUB_NAME, source.LATITUDE, source.LONGITUDE, source.HUB_TYPE);
